name = "AI-Swarm"
uid = "a13ac591-b2d9-4d94-0051-3d4b3cce6b97"
version = 51
copyright = "2019 SilentAzraeel"
description = "Welcome to Swarm. What is Swarm? Swarm is a AI Improvement Mod, Swarm wants to make the AI; Smart and Tough to be beat with the goal of reaching a level of truly Competitive AI. That Can Teach New Players and Help Everyone Get Better. If your playing 20x20 - Recommended Settings: 600 - 700 AI Unit Cap, and  1 AIx MAX. REQUIRES MOD AI-UVESO."
author = "SilentAzraeel"
url = ""
icon = "/mods/AI-Swarm/icon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
