name = "AI-Swarm"
uid = "a13ac591-b2d9-4d94-0284-3d4b3cce6b97"
version = 284
copyright = "2021 Azraeel"
description = "Welcome to Swarm. What is Swarm? Swarm is a AI Improvement Mod, Swarm wants to make the AI; Smart and Tough to be beat with the goal of reaching a level of truly Competitive AI. That Can Teach New Players and Help Everyone Get Better. REQUIRES AI-Uveso for Map Marker Generator!!!! 219 Version - 2021 Rainbow Cup III Tournment Special Update!"
author = "Azraeel"
url = ""
icon = "/mods/AI-Swarm/icon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
